### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by ghost** [kivy/audiostream#23]
Have installed Kivy, and now trying to install Audiostream, but get an error: 
```
>pip3 install git+https://github.com/kivy/audiostream.git
Collecting git+https://github.com/kivy/audiostream.git
  Cloning https://github.com/kivy/audiostream.git to /tmp/pip-uhs2_2ti-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-uhs2_2ti-build/setup.py", line 22
        print 'Cython import ignored'
                                    ^
    SyntaxError: Missing parentheses in call to 'print'
```
Why this could happened? 
I have Cython v0.26
```
>pip3 list | grep Cython
Cython (0.26)
```

**Comment by dolang** [comment]
Hmm, looks like this project's `setup.py` was written for Python 2 only. See [line 22](https://github.com/kivy/audiostream/blob/master/setup.py#L22) In Python 3 `print` needs parentheses. You should probably try again with Python 2 (or fix it manually, but no guarantees, there are probably other incompatibilities).

      File "/tmp/pip-uhs2_2ti-build/setup.py", line 22
        print 'Cython import ignored'
                                    ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by andre-57** [comment]
yep it worked. reinstall kivy and audiostream with python 2. that error gone but now I have another one:
```
>pip install git+https://github.com/kivy/audiostream.git
...
urity build/temp.linux-x86_64-2.7/audiostream/sources/thread.o -lSDL -lSDL_mixer 
-o build/lib.linux-x86_64-2.7/audiostream/sources/thread.so
  /usr/bin/ld: cannot find -lSDL
  /usr/bin/ld: cannot find -lSDL_mixer
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  Failed building wheel for audiostream
```
and if i do "pip install sdl" or "pip install lSDL", it gives me:
```
Could not find a version that satisfies the requirement sdl (from versions: )
No matching distribution found for sdl
```

**Comment by andre-57** [comment]
Finally found the solution.. 
```
>sudo apt-get install libsdl1.2-dev
>sudo apt-get install libsdl-mixer1.2-dev
```
and then:
```
>pip install git+https://github.com/kivy/audiostream.git
...
Successfully installed audiostream-0.2
```

**Comment by dolang** [comment]
Someone would need to take the time and port it. Myself, I haven't used this yet, so I can't really say, but it doesn't look like a big project. SDL2 should already be supported, see #19.

Maybe you want to try that yourself and create a pull request?

**Comment by willandru** [comment]
I had to do this in LINUX Debian-like 

`pip install wheel`

THEN :

`pip install git+https://github.com/kivy/audiostream.git `
or
`pip install git+https://github.com/kivy/audiostream.git --no-cache-dir --no-build-isolation`

**Comment by Voloveee** [comment]
Hello, 

I have enermous problem with audtiostream installation. I've tried literally everything, without success.
I want to install it on Windows, Python 3.7.
I tried with:
`C:\Temp\Kamil\audiostream-master>python setup.py install`
and I got:
`running install
running build
running build_py
running build_ext
building 'audiostream.sources.thread' extension
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/SDL -I. -I/usr/include/SDL -IC:\Users\username\AppData\Local\Programs\Python\Python37\include -IC:\Users\username\AppData\Local\Programs\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcaudiostream\sources\thread.c /Fobuild\temp.win-amd64-3.7\Release\audiostream\sources\thread.obj -ggdb -O2
cl : Wiersz polecenia warning D9002 : ignorowanie nieznanej opcji „-ggdb”
thread.c
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\username\AppData\Local\Programs\Python\Python37\libs /LIBPATH:C:\Users\username\AppData\Local\Programs\Python\Python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" SDL.lib SDL_mixer.lib /EXPORT:PyInit_thread build\temp.win-amd64-3.7\Release\audiostream\sources\thread.obj /OUT:build\lib.win-amd64-3.7\audiostream\sources\thread.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\audiostream\sources\thread.cp37-win_amd64.lib
LINK : fatal error LNK1181: nie można otworzyć pliku wejściowego „SDL.lib”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181`

What can be the problem here? I reinstalled Python few times - tried with different versions. It didn't help, though.. 
I would appreciate any suggestion, hint, idea.

**Comment by Julian-O** [comment]
@Voloveee: Please take it to our [support channels(https://github.com/kivy/kivy/blob/master/CONTACT.md)

**Comment by Julian-O** [comment]
Closing main question as fixed/support.
